from pydantic import BaseModel, Field, BeforeValidator
from enum import Enum
from typing import List, Optional, Annotated

# --- 1. Validators ---
def to_upper(v: str) -> str:
    """Helper to ensure verdict is always uppercase before validation."""
    if isinstance(v, str):
        return v.upper()
    return v

# --- 2. Enums ---
class Lifestyle(str, Enum):
    SEDENTARY = "sedentary"
    ACTIVE = "active"
    VERY_ACTIVE = "very_active"

class Verdict(str, Enum):
    RECOMMENDED = "RECOMMENDED"
    CAUTION = "CAUTION"
    AVOID = "AVOID"

# --- 3. Sub-Models ---

class UserDetails(BaseModel):
    """
    Profile of a specific person being analyzed.
    """
    height: float = Field(..., description="Height in cm")
    weight: float = Field(..., description="Weight in kg")
    age: int = Field(..., description="Age in years")
    lifestyle: Lifestyle = Field(..., description="Activity level")
    
    # Clinical Context
    label: str = Field(..., description="Display label e.g. 'Renal Patient'")
    conditions: List[str] = Field(default=[], description="List of medical conditions e.g. ['Type 2 Diabetes', 'Hypertension']")

class UserScenario(BaseModel):
    """
    The AI's verdict for a specific health scenario.
    """
    scenario: str = Field(..., description="The scenario being analyzed (e.g., 'Renal Safety').")
    
    # [FIX] This 'Annotated' wrapper automatically uppercases the input 
    # BEFORE checking strictly against the Enum.
    verdict: Annotated[Verdict, BeforeValidator(to_upper)] = Field(..., description="The final judgment.")
    
    reasoning: str = Field(..., description="Clinical explanation for the verdict.")

class Evidence(BaseModel):
    """
    A specific piece of verified data found during search.
    """
    notes: str = Field(..., description="The key finding or fact extracted from the source.")
    source_link: str = Field(..., description="The direct URL to the source.")
    
    link_status: bool = Field(
        default=True, 
        description="True if the link was successfully accessed (HTTP 200)."
    )
    
    link_contains_notes_in_content: bool = Field(
        default=True, 
        description="True if the 'notes' text was verified to exist inside the page content."
    )

    quote: Optional[str] = Field(None, description="A direct quote from the text if available.")
    relevant_scenarios: List[str] = Field(default=[], description="Which scenarios this evidence supports.")

# --- 4. Main Output Model ---

class RecipeContext(BaseModel):
    """
    The final complete report generated by the AI Agent.
    """
    meal_id: Optional[str] = None
    title: str = Field(..., description="Title of the recipe.")
    
    user_details: List[UserDetails] = Field(..., description="List of users this was analyzed against.")
    user_scenario: List[UserScenario] = Field(..., description="The verdicts for the users.")
    evidence: List[Evidence] = Field(..., description="Verified scientific sources backing the verdicts.")
    
    scientific_summary: str = Field(..., description="High-level clinical summary of the analysis.")
    health_score: int = Field(..., description="Overall health score (0-100).")